name: StackMob
main: uk.antiperson.stackmob.StackMob
version: ${project.version}
api-version: 1.15
softdepend: [ WorldGuard, MythicMobs, ProtocolLib, Citizens, Jobs, mcMMO ]
author: antiPerson
website: https://www.spigotmc.org/resources/stackmob-enhance-your-servers-performance-without-the-sacrifice.29999/
description: A plugin that aims to improve performance by 'stacking' entities together, with attempts to perserve game mechanics.
commands:
  stackmob:
    aliases: [ sm ]
    permission: stackmob.admin
    description: The main command of stackmob, which allows for maniplulation of stacks.
    permission-message: No permission!